# name: Check Links

# on:
#   repository_dispatch:
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - main
#   schedule:
#     - cron: "0 0 * * *"

# jobs:
#   linkChecker:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Link Checker
#         id: lychee
#         uses: lycheeverse/lychee-action@v1
#         env:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#         with:
#           fail: true
#           debug: false
#           args: --verbose --no-progress --base . -E './**/*.md' './**/*.mdx'

#       - name: Create Issue From File
#         if: env.lychee_exit_code != 0
#         uses: peter-evans/create-issue-from-file@v4
#         with:
#           title: Link Checker Report
#           content-filepath: ./lychee/out.md
#           labels: report, automated issue
